dual_task:
  batch_size: 32
  learning_rate: 0.001
  max_epochs: 100
  pre_train_epochs: 50
  lr_decay_every_n_epoch: 80
  lr_decay_rate: 0.4
  train_sample: 5000
  loss:
    alpha: 0.03 # spectral

mlp_wavelet:
  learning_rate: 0.001
  batch_size: 256
  max_epochs: 100
  lr_decay_every_n_epoch: 80
  lr_decay_rate: 0.5
  qt_seismic_distortions: 10
  train_sample: 100000

time_shift:
  batch_size: 32
  learning_rate: 0.001
  max_epochs: 100
  lr_decay_every_n_epoch: 40
  lr_decay_rate: 0.5
  train_distortions: 1 #500